USE arelore_education;

-- 1) 插入检测类型（MBTI）
INSERT INTO `user_detection_type`
(`type_code`, `type_name`, `type_description`, `modifier`, `extra_info`)
VALUES
    ('MBTI', 'MBTI性格测试', '迈尔斯-布里格斯性格类型测试（40题版）', 'system',
     '{"version":"v1.0","questionCount":40,"dimensions":["E/I","S/N","T/F","J/P"]}');

-- 2) 插入题目（40题）
INSERT INTO `user_detection_question`
(`type_code`, `question_code`, `question_name`, `question_order`, `question_description`, `options`, `modifier`, `extra_info`)
VALUES
-- E / I
('MBTI','MBTI_Q001','在社交场合中你通常会？',1,'偏向外向或内向判断',
 '[{"key":"A","text":"主动认识很多新朋友","dimension":"E"},{"key":"B","text":"与熟悉的人小范围交流","dimension":"I"}]',
 'system','{"dimensionPair":"E/I","a":"E","b":"I"}'),
('MBTI','MBTI_Q002','周末结束后你更常感觉？',2,'能量来源判断',
 '[{"key":"A","text":"和人相处后更有活力","dimension":"E"},{"key":"B","text":"独处后更有活力","dimension":"I"}]',
 'system','{"dimensionPair":"E/I","a":"E","b":"I"}'),
('MBTI','MBTI_Q003','遇到问题时你更倾向？',3,'思考起点偏好',
 '[{"key":"A","text":"先找人讨论","dimension":"E"},{"key":"B","text":"先自己想清楚","dimension":"I"}]',
 'system','{"dimensionPair":"E/I","a":"E","b":"I"}'),
('MBTI','MBTI_Q004','在团队会议里你通常？',4,'表达方式判断',
 '[{"key":"A","text":"边说边想，快速表达","dimension":"E"},{"key":"B","text":"想好后再发言","dimension":"I"}]',
 'system','{"dimensionPair":"E/I","a":"E","b":"I"}'),
('MBTI','MBTI_Q005','结识新同事时你会？',5,'主动程度判断',
 '[{"key":"A","text":"主动开启话题","dimension":"E"},{"key":"B","text":"等待自然熟悉","dimension":"I"}]',
 'system','{"dimensionPair":"E/I","a":"E","b":"I"}'),
('MBTI','MBTI_Q006','做决定前你更常？',6,'信息收集方式判断',
 '[{"key":"A","text":"广泛征求意见","dimension":"E"},{"key":"B","text":"先内化再定结论","dimension":"I"}]',
 'system','{"dimensionPair":"E/I","a":"E","b":"I"}'),
('MBTI','MBTI_Q007','陌生环境下你更容易？',7,'适应方式判断',
 '[{"key":"A","text":"快速参与互动","dimension":"E"},{"key":"B","text":"先观察再参与","dimension":"I"}]',
 'system','{"dimensionPair":"E/I","a":"E","b":"I"}'),
('MBTI','MBTI_Q008','你更偏好哪种沟通？',8,'沟通偏好判断',
 '[{"key":"A","text":"频繁即时沟通","dimension":"E"},{"key":"B","text":"深度但不频繁沟通","dimension":"I"}]',
 'system','{"dimensionPair":"E/I","a":"E","b":"I"}'),
('MBTI','MBTI_Q009','当你有好主意时会？',9,'表达时机判断',
 '[{"key":"A","text":"马上说出来试试看","dimension":"E"},{"key":"B","text":"完善后再分享","dimension":"I"}]',
 'system','{"dimensionPair":"E/I","a":"E","b":"I"}'),
('MBTI','MBTI_Q010','长时间多人活动后你通常？',10,'恢复方式判断',
 '[{"key":"A","text":"还能继续社交","dimension":"E"},{"key":"B","text":"需要独处充电","dimension":"I"}]',
 'system','{"dimensionPair":"E/I","a":"E","b":"I"}'),

-- S / N
('MBTI','MBTI_Q011','学习新事物时你更喜欢？',11,'信息处理偏好',
 '[{"key":"A","text":"从具体案例入手","dimension":"S"},{"key":"B","text":"先看整体框架与概念","dimension":"N"}]',
 'system','{"dimensionPair":"S/N","a":"S","b":"N"}'),
('MBTI','MBTI_Q012','你更关注？',12,'关注点判断',
 '[{"key":"A","text":"现实与细节","dimension":"S"},{"key":"B","text":"可能性与趋势","dimension":"N"}]',
 'system','{"dimensionPair":"S/N","a":"S","b":"N"}'),
('MBTI','MBTI_Q013','描述事情时你倾向？',13,'表达方式判断',
 '[{"key":"A","text":"按事实和步骤描述","dimension":"S"},{"key":"B","text":"加入联想和隐喻","dimension":"N"}]',
 'system','{"dimensionPair":"S/N","a":"S","b":"N"}'),
('MBTI','MBTI_Q014','面对未知任务你更常？',14,'切入方式判断',
 '[{"key":"A","text":"先看已有经验怎么做","dimension":"S"},{"key":"B","text":"先想有没有新办法","dimension":"N"}]',
 'system','{"dimensionPair":"S/N","a":"S","b":"N"}'),
('MBTI','MBTI_Q015','你更容易记住？',15,'记忆偏好判断',
 '[{"key":"A","text":"具体事实和细节","dimension":"S"},{"key":"B","text":"核心概念和灵感","dimension":"N"}]',
 'system','{"dimensionPair":"S/N","a":"S","b":"N"}'),
('MBTI','MBTI_Q016','工作中你更信任？',16,'信任依据判断',
 '[{"key":"A","text":"已经验证的方法","dimension":"S"},{"key":"B","text":"创新和直觉判断","dimension":"N"}]',
 'system','{"dimensionPair":"S/N","a":"S","b":"N"}'),
('MBTI','MBTI_Q017','你更喜欢哪类讨论？',17,'讨论偏好判断',
 '[{"key":"A","text":"落地执行与资源安排","dimension":"S"},{"key":"B","text":"愿景方向与长期可能","dimension":"N"}]',
 'system','{"dimensionPair":"S/N","a":"S","b":"N"}'),
('MBTI','MBTI_Q018','阅读文章时你更关注？',18,'阅读关注点判断',
 '[{"key":"A","text":"事实依据和数据","dimension":"S"},{"key":"B","text":"观点洞察和启发","dimension":"N"}]',
 'system','{"dimensionPair":"S/N","a":"S","b":"N"}'),
('MBTI','MBTI_Q019','遇到新机会时你会？',19,'决策关注点判断',
 '[{"key":"A","text":"先评估现实可行性","dimension":"S"},{"key":"B","text":"先设想潜在空间","dimension":"N"}]',
 'system','{"dimensionPair":"S/N","a":"S","b":"N"}'),
('MBTI','MBTI_Q020','你更喜欢的工作说明是？',20,'任务定义偏好',
 '[{"key":"A","text":"明确具体、边界清晰","dimension":"S"},{"key":"B","text":"开放探索、保留弹性","dimension":"N"}]',
 'system','{"dimensionPair":"S/N","a":"S","b":"N"}'),

-- T / F
('MBTI','MBTI_Q021','做决策时你更优先？',21,'决策依据判断',
 '[{"key":"A","text":"逻辑一致与客观标准","dimension":"T"},{"key":"B","text":"关系感受与人的影响","dimension":"F"}]',
 'system','{"dimensionPair":"T/F","a":"T","b":"F"}'),
('MBTI','MBTI_Q022','评价方案时你更看重？',22,'评价标准判断',
 '[{"key":"A","text":"效率与结果","dimension":"T"},{"key":"B","text":"团队接受度","dimension":"F"}]',
 'system','{"dimensionPair":"T/F","a":"T","b":"F"}'),
('MBTI','MBTI_Q023','同事出错时你更可能？',23,'反馈方式判断',
 '[{"key":"A","text":"直接指出问题并纠正","dimension":"T"},{"key":"B","text":"先照顾情绪再沟通","dimension":"F"}]',
 'system','{"dimensionPair":"T/F","a":"T","b":"F"}'),
('MBTI','MBTI_Q024','遇到分歧时你更倾向？',24,'冲突处理判断',
 '[{"key":"A","text":"据理力争找最优解","dimension":"T"},{"key":"B","text":"先维持关系和谐","dimension":"F"}]',
 'system','{"dimensionPair":"T/F","a":"T","b":"F"}'),
('MBTI','MBTI_Q025','你更容易被说服于？',25,'说服依据判断',
 '[{"key":"A","text":"严密论证","dimension":"T"},{"key":"B","text":"价值共鸣","dimension":"F"}]',
 'system','{"dimensionPair":"T/F","a":"T","b":"F"}'),
('MBTI','MBTI_Q026','你认为“公平”更接近？',26,'公平定义判断',
 '[{"key":"A","text":"规则一致适用于所有人","dimension":"T"},{"key":"B","text":"结合个体情况灵活处理","dimension":"F"}]',
 'system','{"dimensionPair":"T/F","a":"T","b":"F"}'),
('MBTI','MBTI_Q027','你给建议时更常？',27,'建议风格判断',
 '[{"key":"A","text":"给出问题分析与行动方案","dimension":"T"},{"key":"B","text":"先肯定对方再给建议","dimension":"F"}]',
 'system','{"dimensionPair":"T/F","a":"T","b":"F"}'),
('MBTI','MBTI_Q028','面对规则执行你更看重？',28,'执行偏好判断',
 '[{"key":"A","text":"一致性与原则","dimension":"T"},{"key":"B","text":"人情与实际处境","dimension":"F"}]',
 'system','{"dimensionPair":"T/F","a":"T","b":"F"}'),
('MBTI','MBTI_Q029','在复盘中你更关注？',29,'复盘关注点判断',
 '[{"key":"A","text":"哪里逻辑不成立","dimension":"T"},{"key":"B","text":"谁的体验受影响","dimension":"F"}]',
 'system','{"dimensionPair":"T/F","a":"T","b":"F"}'),
('MBTI','MBTI_Q030','你更欣赏的领导风格是？',30,'领导偏好判断',
 '[{"key":"A","text":"理性果断、标准明确","dimension":"T"},{"key":"B","text":"包容体贴、重视人心","dimension":"F"}]',
 'system','{"dimensionPair":"T/F","a":"T","b":"F"}'),

-- J / P
('MBTI','MBTI_Q031','你更偏好的节奏是？',31,'节奏偏好判断',
 '[{"key":"A","text":"计划先行、按时推进","dimension":"J"},{"key":"B","text":"灵活调整、顺势而为","dimension":"P"}]',
 'system','{"dimensionPair":"J/P","a":"J","b":"P"}'),
('MBTI','MBTI_Q032','面对待办事项你通常？',32,'任务管理判断',
 '[{"key":"A","text":"尽快清空清单","dimension":"J"},{"key":"B","text":"保留选项，临近再定","dimension":"P"}]',
 'system','{"dimensionPair":"J/P","a":"J","b":"P"}'),
('MBTI','MBTI_Q033','你更喜欢旅行方式？',33,'安排偏好判断',
 '[{"key":"A","text":"行程提前规划完整","dimension":"J"},{"key":"B","text":"到当地再决定安排","dimension":"P"}]',
 'system','{"dimensionPair":"J/P","a":"J","b":"P"}'),
('MBTI','MBTI_Q034','任务截止前你更常？',34,'时间管理判断',
 '[{"key":"A","text":"提前完成留余量","dimension":"J"},{"key":"B","text":"截止前冲刺完成","dimension":"P"}]',
 'system','{"dimensionPair":"J/P","a":"J","b":"P"}'),
('MBTI','MBTI_Q035','办公环境你更希望？',35,'环境偏好判断',
 '[{"key":"A","text":"整洁有序、物品归位","dimension":"J"},{"key":"B","text":"有点随性但找得到","dimension":"P"}]',
 'system','{"dimensionPair":"J/P","a":"J","b":"P"}'),
('MBTI','MBTI_Q036','你对变化的态度更像？',36,'变化反应判断',
 '[{"key":"A","text":"希望变化可预测并提前通知","dimension":"J"},{"key":"B","text":"乐于应对临时变化","dimension":"P"}]',
 'system','{"dimensionPair":"J/P","a":"J","b":"P"}'),
('MBTI','MBTI_Q037','你做决定时更倾向？',37,'决策闭环判断',
 '[{"key":"A","text":"尽快拍板并执行","dimension":"J"},{"key":"B","text":"持续观察再决定","dimension":"P"}]',
 'system','{"dimensionPair":"J/P","a":"J","b":"P"}'),
('MBTI','MBTI_Q038','你处理邮件/消息更常？',38,'处理方式判断',
 '[{"key":"A","text":"及时分类和回复","dimension":"J"},{"key":"B","text":"集中批量处理","dimension":"P"}]',
 'system','{"dimensionPair":"J/P","a":"J","b":"P"}'),
('MBTI','MBTI_Q039','项目推进中你更偏好？',39,'推进偏好判断',
 '[{"key":"A","text":"里程碑明确、定期检查","dimension":"J"},{"key":"B","text":"目标明确、过程弹性","dimension":"P"}]',
 'system','{"dimensionPair":"J/P","a":"J","b":"P"}'),
('MBTI','MBTI_Q040','对“完成”与“完善”你更像？',40,'收尾偏好判断',
 '[{"key":"A","text":"先按计划完成再优化","dimension":"J"},{"key":"B","text":"边做边改直到满意","dimension":"P"}]',
 'system','{"dimensionPair":"J/P","a":"J","b":"P"}');